ajax
jezman/qna pull request #4
Opened 2018-12-12 17:17 UTC by jezman

2018-12-13 11:12 UTC, vkurennov requested changes

2018-12-13 11:12 UTC, vkurennov commented on app/assets/javascripts/answers.js
> +   $('.answers').on('click', '.best-answer-link', function(e) {
А этот обработчик зачем? Если только для отладки, то надо его удалить

2018-12-13 11:12 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    return unless current_user.author?(@answer)
экшены в контроллерах это не совсем обычные методы, потому что они должны формировать ответ на http-запрос. Поэтому нельзя просто сделать return из метода - ответ-то какой клиенту послать?

2018-12-13 11:12 UTC, vkurennov commented on app/models/answer.rb
> +  scope :best, -> { where best: true }
у where и других методов аргументы принято указывать в скобках, исключение - методы dsl, вроде валидаций, ассоциаций или хелперов в видах.

2018-12-13 11:12 UTC, vkurennov commented on app/models/answer.rb
> +      raise 'only one answer can be the best' if question.answers.best.count > 1
Не стоит делать это через ислючение, в продакшене пользователь увидит 500ю ошибку, а не вразумительное сообщение. Лучше сделать через валидацию.

2018-12-13 11:12 UTC, vkurennov commented on app/views/questions/update.js.erb
> +  $('.question-title').html('<%= j @question.title %>');
Тут лучше перерендерить весь блок вопроса, чем по отдельным полям менять

2018-12-13 11:12 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
Пропустил в прошлой проверке: при успешном создании ответа надо также проверить связь с залогиненным юзером

2018-12-13 11:12 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>  RSpec.describe QuestionsController, type: :controller do
Тут при успешном создании тоже надо проверить связь с залогиненным юзером

2018-12-13 11:12 UTC, vkurennov commented on spec/features/answer/best_spec.rb
> +    scenario 'link to choose the best answer available' do
Не нужно писать отдельный сценарий на наличие ссылки. ее наличие неявно проверяется при клике в другом сценарии

2018-12-13 11:12 UTC, vkurennov commented on spec/features/answer/best_spec.rb
> +    scenario 'can change the best answer' do
Это по сути тот же сценарий, что и выше, только на других объектах. Достаточно одного из них

2018-12-13 11:12 UTC, vkurennov commented on spec/features/answer/best_spec.rb
> +feature 'Best answer', %q{
Нужен сценарий, проверяющий, что лучший ответ стал первым в списке

2018-12-13 11:44 UTC, jezman commented on spec/controllers/questions_controller_spec.rb
>  RSpec.describe QuestionsController, type: :controller do
У меня же есть проверка, вроде как
https://github.com/jezman/qna/blob/cd02f09cc6c44e23aeb99cc2f8c94ade2e18b4c2/spec/controllers/questions_controller_spec.rb#L56

2018-12-13 14:03 UTC, jezman commented on spec/features/answer/best_spec.rb
> +    scenario 'best answer is first in list' do
Я не понимаю, почему если убрать 43 строку в сценарии, тест не проходит.

2018-12-14 11:41 UTC, vkurennov requested changes

2018-12-14 11:41 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user.author?(@answer)
А что будет, если условие не выполнится? Отрендерится тот же самый update.js.erb, но это как-то не совсем верно, зачем обновлять ответ, если он не был обновлен?

2018-12-14 11:41 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question.update(question_params) if current_user.author?(@question)
Тут тоже надо предусмотреть обработку, когда у нас не автор

2018-12-14 11:41 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>  RSpec.describe QuestionsController, type: :controller do
Да, точно, просто подмал, что раз нет в контроллере ответов, то и тут, а гитхаб прошлые изменения скрывает, поэтому не заметил, что здесь тест уже есть

2018-12-14 11:41 UTC, vkurennov commented on spec/features/answer/best_spec.rb
> +    scenario 'best answer is first in list' do
Возможно, js-ответ не так быстро отрабатывает, а тесты не дожидаются, пока на странице что-то призойдет. Попробуй вместо этой строки поставить sleep(1), если с ней будет проходить, а без нее - нет, то проблема точно в этом. Как ее решать, можно прочитать [здесь](http://connect.thinknetica.com/t/ajax/976) (cм. лучшее решение в конце поста).

2018-12-14 11:41 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      expect(answer).to be_best
Вообще, в юнит-тестах принято правило "один тест - один expect", иногда можно от него отступать, но должно быть не более 2-х expect, так что надо разбить это на несколько тестов.

2018-12-15 03:29 UTC, vkurennov approved these changes

2018-12-15 09:20 UTC, merged