The user can view the rewards he received.
jezman/qna pull request #8
Opened 2019-01-10 08:51 UTC by jezman

2019-01-10 13:24 UTC, vkurennov requested changes

2019-01-10 13:49 UTC, jezman commented on spec/controllers/answers_controller_spec.rb
> +      it 'assigns the question badge to user badge' do
```ruby
    let(:author) { create(:user) }
    let(:any_user) { create(:user) }
    let!(:new_question) { create(:question, user: author) }
    let!(:badge) { create(:badge, question: new_question) }
    let!(:answer) { create(:answer, question: new_question, user: any_user) }
```
Так ведь запрос должен делаеть автор вопроса. А выдоваться бейдж должен автору ответа.  В тесте проверяю что бейдж присвоен автору ответа или я ошибаюсь в чем то?

2019-01-11 07:55 UTC, vkurennov approved these changes

2019-01-11 07:55 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      it 'assigns the question badge to user badge' do
Да, ты прав, меня ввело в заблуждение название `any_user`, вот что значит сила нейминга. Стоили назвать его `answer_author`, тогда все читалось бы значительно лучше.

2019-01-11 09:19 UTC, merged